version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=news
      - DB_USER=postgres
      - DB_PASSWORD=2669526rain
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2669526rain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
